language: ruby

rvm:
  - jruby-19mode
  - 2.1.1

script: "bundle exec rake spec"

before_script:
  - psql -c 'create database embeds_many_test;' -U postgres
  - psql embeds_many_test -c 'create extension hstore;' -U postgres

addons:
  postgresql: '9.3'